# -*- encoding : utf-8 -*-
require "spec_helper"

describe Admin::ExportUsersWorker do
  describe '#perform' do
    let(:email) { "user@example.com" }
    let(:file_name) { "users.csv" }

    it "should call UserReport#generate_csv to create the CSV file" do
      UserReport.should_receive(:generate_csv)

      Admin::ExportUsersWorker.perform(email)
    end

    it "should call Admin::UserExportMailer.csv_ready with the received email and filename generated by UserReport.generate_csv" do
      UserReport.stub(:generate_csv).and_return(file_name)

      Admin::UserExportMailer.should_receive(:csv_ready).with(email, file_name).and_return(mock.as_null_object)
      Admin::ExportUsersWorker.perform(email)
    end
  end
end
